version: "2"
services:
  db:
    image: mysql:8.0.19
    container_name: db
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4306:3306"
